name: beacon_settings
description: A companion package to `state_beacon` that makes it easy to manage key-value based settings.
version: 0.0.2
repository: https://github.com/btrautmann/beacon_settings

environment:
  sdk: ^3.3.1

dependencies:
  equatable: ^2.0.5
  meta: ^1.11.0
  state_beacon_core: ^0.43.3

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  test: ^1.24.0
